port: ":8080"
logLevel: "info"
jwtSecret: "default-very-secure-jwt-secret-key-change-in-production"
jwtExpiration: 60
consulAddress: ""
natsAddress: "nats://localhost:4222"

corsAllowed:
  origins:
    - "http://localhost:3000"
    - "http://localhost:8080"
  methods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
    - "OPTIONS"
    - "PATCH"
  headers:
    - "Accept"
    - "Authorization"
    - "Content-Type"
    - "X-CSRF-Token"
    - "X-Request-ID"
    - "X-Requested-With"
